name: file3
on:
  workflow_call:
    inputs:
      platform:
        description: Platform
        type: Sting
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo "${{ inputs.platform }}"