name: file3
description: Setup application environment for OneApp
inputs:
 platform:
   description: Platform

runs:
  using: "composite"
  steps:
    - name: print
      shell: bash
      run: |
       echo "${{ inputs.platform }}"