name: check_release_week
on:
  workflow_call:
    inputs:
     release_type:
        description: Specify Release type (production, stage)
        required: true
        type: string
    outputs:
      release_week:
        description: "Week Number"
        value: ${{ jobs.week-check.outputs.release_week }}

jobs:
  week-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if release week
        id: release_week
        run: |
          #!/bin/bash
          # Get release type
          echo "${{ toJSON(github.event.inputs) }}"
          release_type=${{ github.event.inputs.release_type }}
          # Calculate the number of weeks since the reference date (Mon Jan 1st, 2024)
          # note: this formatting is only for ubuntu
          weeks=$(( ($(date +%V | sed 's/^0*//' ) - $(date -d '2024-01-01' +%V | sed 's/^0*//')) ))
          # If the number of fortnights since the reference date is odd and it's production build, then it's an "on" week
          # If the number of fortnights since the reference date is even and it's stage build, then it's an "on" week
          
          echo " release type is $release_type"
          if ([ $((weeks % 2)) == 1 ] && [ "$release_type" == "production" ]) || ([ $((weeks % 2)) == 0 ] && [ "$release_type" == "stage" ]); then
             echo "week: $weeks - Release is this week. Continuing release activities…"
              echo "release_week=true" >> $GITHUB_OUTPUT
          else
              echo "week: $weeks - Release is not this week. Skipping release activities…"
              echo "release_week=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      release_week: ${{ steps.release_week.outputs.release_week }}