name: file1
on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform
        type: string
jobs:
  first_job:
      runs-on: ubuntu-latest
      steps:
          - name: Run first job
            run: |
              echo "The platform is ${{ inputs.platform }}"
  second_job:
        uses: ./.github/workflows/file2.yml
        with:
          input1: ${{ inputs.platform }}
  third_job:
    runs-on: ubuntu-latest
    id: third_job
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/C_Action
        with:
          platform: ${{ inputs.platform }}
      - name: Run
        run: |
          echo "out= this is 3rd step output" >> $GITHUB_OUTPUT

  output_job:
    runs-on: ubuntu-latest
    needs: [third_job]
    steps:
      - name: print outpuy
        run: |
          echo "${{ steps.third_job.output.out }}"