name: file1
on:
  workflow-dispatch:
    inputs:
      platform:
        description: Platform
        type: String
  jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:
        step_one:
          - name: Run first job
            run: |
              echo "The platform is ${{ inputs.platform }}"
          - name: Run file2
            use: .github/workflows/file2.yml
            with:
              input1: {{ inputs.platform }}