name: file1
on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform
        type: string
jobs:
  first_job:
      runs-on: ubuntu-latest
      steps:
          - name: Run first job
            run: |
              echo "The platform is ${{ inputs.platform }}"
  second_job:
        uses: ./.github/workflows/file2.yml@main
        with:
          input1: ${{ inputs.platform }}