name: file1
on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform
        type: string
jobs:
  first_job:
      runs-on: ubuntu-latest
      steps:
          - name: Run first job
            run: |
              echo "The platform is ${{ inputs.platform }}"
  second_job:
        uses: ./.github/workflows/file2.yml
        with:
          input1: ${{ inputs.platform }}
  third_job:
    runs-on: ubuntu-latest
    outputs:
      out1: ${{ steps.third_step_id.outputs.out}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/C_Action
        with:
          platform: ${{ inputs.platform }}
      - name: Run
        id: third_step_id
        run: |
          echo "out= this is 3rd step output" >> $GITHUB_OUTPUT
      - name: Print
        run: |
          echo "${{ steps.third_step_id.outputs.out}}"

  output_job:
    runs-on: ubuntu-latest
#    needs: [third_job]
    steps:
      - name: print output
        run: |
          echo "${{ needs.third_job.outputs.out1 }}"