name: file2
on:
  workflow_call:
    inputs:
      input1:
        description: First input
        type: string
    outputs:
      workflowVar:
        value: ${{ jobs.first_job.outputs.out }}
jobs:
    first_job:
      runs-on: ubuntu-latest
      outputs:
        out: ${{ steps.step_id.outputs.workflowVar}}
      steps:
        - name: first input
          id: step_id
          run: |
            echo " your first input is ${{ inputs.input1 }}"
            echo "workflowVar = this is file2" >>$GITHUB_OUTPUT
