name: file1
on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform
        type: String
jobs:
  first_job:
      runs-on: ubuntu-latest
      steps:
          - name: checkout
            uses: actions/checkout@v2
          - name: Run first job
            run: |
              echo "The platform is ${{ inputs.platform }}"
          - name: Run file2
            uses: .github/workflows/file2.yml@main
            with:
              input1: {{ inputs.platform }}