on: [push]
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    name: job to say hello world
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: ./
        id: hello
        with:
          who-to-greet: hanaa
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        
      
