name: scheduled-android-production-release
on:
  workflow_dispatch:
  schedule:
    # Runs at 3am on Monday [biweekly check inside the job]
    - cron: 0 3 * * 1
jobs:
  week-check:
     uses: HanaaMAldaly/hello-world-js-action/.github/workflows/biweekSchedule.yml@main
     with:
       release_type: "production"
  android-production-release:
    runs-on: ubuntu-latest
    needs: [week-check]
    if: ${{ needs.week-check.outputs.release_week == 'true' }}
    steps: 
      - name: Run Script
        run: |
          echo Run release activities
          echo Release value is ${{ needs.week-check.outputs.release_week }}
