name: test
on:
  [workflow_dispatch, pull_request]
jobs:
  test_action:
   uses: HanaaMAldaly2/MyMovie/.github/workflows/reusable.yml@main
   with:
     path: .github/labeler.yml
   secrets: 
     token: ${{secrets.TOKEN}}
    
    
